/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.shohojatri;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jahirdipu
 */
public class ShohoJatriUI extends javax.swing.JFrame {

    /**
     * Creates new form ShohoJatriUI
     */
    public ShohoJatriUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        HomeSignIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HomeSignUp = new javax.swing.JButton();
        HomeExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        UserSignUpBtn = new javax.swing.JButton();
        RiderSignUpBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        RiderSignInBtn = new javax.swing.JButton();
        AdminSignInBtn = new javax.swing.JButton();
        UserSignInBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        UserSignUpConfirmBtn = new javax.swing.JButton();
        UserFullNameReg = new javax.swing.JTextField();
        UserMobileReg = new javax.swing.JTextField();
        UserUsernameReg = new javax.swing.JTextField();
        UserPassReg = new javax.swing.JPasswordField();
        ShowUserPassSignUp = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        RiderFullNameReg = new javax.swing.JTextField();
        RiderUsernameReg = new javax.swing.JTextField();
        RiderPassReg = new javax.swing.JPasswordField();
        RiderMobileReg = new javax.swing.JTextField();
        RiderSignUpBtnReg = new javax.swing.JButton();
        RiderVehicleReg = new javax.swing.JTextField();
        RiderAddressReg = new javax.swing.JTextField();
        ShowRiderPassSignUp = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        RequestRide = new javax.swing.JButton();
        HistoryUser = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        AcceptRide = new javax.swing.JButton();
        RiderHistory = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        SeeUsers = new javax.swing.JButton();
        SeeRiders = new javax.swing.JButton();
        AcceptRiders = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        UsernameSignIn = new javax.swing.JTextField();
        UserPassSignIn = new javax.swing.JPasswordField();
        UserSignIn = new javax.swing.JButton();
        ShowUserPassSignIn = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        RidernameSignIn = new javax.swing.JTextField();
        RiderPassSignIn = new javax.swing.JPasswordField();
        ShowRiderPassSignIn = new javax.swing.JCheckBox();
        RiderSignIn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        AdminnameSignIn = new javax.swing.JTextField();
        AdminPassSignIn = new javax.swing.JPasswordField();
        ShowAdminPassSignIn = new javax.swing.JCheckBox();
        AdminSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeSignIn.setText("Sign In");
        HomeSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSignInActionPerformed(evt);
            }
        });
        jPanel2.add(HomeSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 132, 45));

        HomeSignUp.setText("Sign Up");
        HomeSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(HomeSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        HomeExit.setText("Exit");
        HomeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeExitActionPerformed(evt);
            }
        });
        jPanel2.add(HomeExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jTabbedPane1.addTab("Home", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserSignUpBtn.setText("User Sign Up");
        UserSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSignUpBtnActionPerformed(evt);
            }
        });
        jPanel3.add(UserSignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 170, -1, -1));

        RiderSignUpBtn.setText("Rider Sign Up");
        RiderSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderSignUpBtnActionPerformed(evt);
            }
        });
        jPanel3.add(RiderSignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 211, -1, -1));

        jTabbedPane1.addTab("Sign Up", jPanel3);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RiderSignInBtn.setText("Rider Sign In");
        RiderSignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderSignInBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RiderSignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 176, -1, -1));

        AdminSignInBtn.setText("Admin Sign In");
        AdminSignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSignInBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AdminSignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        UserSignInBtn.setText("User Sign In");
        UserSignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSignInBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UserSignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 147, -1, -1));

        jTabbedPane1.addTab("Sign In", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserSignUpConfirmBtn.setText("Sign Up");
        UserSignUpConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSignUpConfirmBtnActionPerformed(evt);
            }
        });
        jPanel4.add(UserSignUpConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 301, -1, -1));

        UserFullNameReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Full Name"));
        jPanel4.add(UserFullNameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 43, 217, 48));

        UserMobileReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Mobile No."));
        jPanel4.add(UserMobileReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 217, 48));

        UserUsernameReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel4.add(UserUsernameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 97, 217, 48));

        UserPassReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        jPanel4.add(UserPassReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 217, 50));

        ShowUserPassSignUp.setText("Show Password");
        ShowUserPassSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUserPassSignUpActionPerformed(evt);
            }
        });
        jPanel4.add(ShowUserPassSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jTabbedPane1.addTab("User Sign Up", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RiderFullNameReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Full Name"));
        jPanel5.add(RiderFullNameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 217, 50));

        RiderUsernameReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel5.add(RiderUsernameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 217, -1));

        RiderPassReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        RiderPassReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderPassRegActionPerformed(evt);
            }
        });
        jPanel5.add(RiderPassReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 217, 50));

        RiderMobileReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Mobile No."));
        jPanel5.add(RiderMobileReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 217, 48));

        RiderSignUpBtnReg.setText("Sign Up");
        RiderSignUpBtnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderSignUpBtnRegActionPerformed(evt);
            }
        });
        jPanel5.add(RiderSignUpBtnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        RiderVehicleReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Type"));
        jPanel5.add(RiderVehicleReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 217, 48));

        RiderAddressReg.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jPanel5.add(RiderAddressReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 217, 48));

        ShowRiderPassSignUp.setText("Show Password");
        ShowRiderPassSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRiderPassSignUpActionPerformed(evt);
            }
        });
        jPanel5.add(ShowRiderPassSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jTabbedPane1.addTab("Rider Sign Up", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RequestRide.setText("Request a ride");
        jPanel6.add(RequestRide, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 114, -1, -1));

        HistoryUser.setText("See history");
        jPanel6.add(HistoryUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jTabbedPane1.addTab("User Portal", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AcceptRide.setText("Accept a ride");
        jPanel7.add(AcceptRide, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        RiderHistory.setText("See history");
        RiderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderHistoryActionPerformed(evt);
            }
        });
        jPanel7.add(RiderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        Account.setText("Account");
        jPanel7.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jTabbedPane1.addTab("Rider Portal", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeeUsers.setText("See Users");
        SeeUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeUsersActionPerformed(evt);
            }
        });
        jPanel8.add(SeeUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 95, -1, -1));

        SeeRiders.setText("See Riders");
        SeeRiders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeRidersActionPerformed(evt);
            }
        });
        jPanel8.add(SeeRiders, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 124, -1, -1));

        AcceptRiders.setText("Accept new rider");
        AcceptRiders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRidersActionPerformed(evt);
            }
        });
        jPanel8.add(AcceptRiders, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jTabbedPane1.addTab("Admin Portal", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Mobile No.", "Vehicle Type", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Vehicle Type");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Address");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        jTabbedPane1.addTab("AcceptApps", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(0, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Mobile No.", "Vehicle Type", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Vehicle Type");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Address");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        jTabbedPane1.addTab("Riders", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setBackground(new java.awt.Color(0, 102, 102));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Full Name", "Username", "Mobile No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        jTabbedPane1.addTab("Users", jPanel11);

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel12.add(UsernameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 96, 190, 50));

        UserPassSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        UserPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPassSignInActionPerformed(evt);
            }
        });
        jPanel12.add(UserPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 190, 50));

        UserSignIn.setText("Sign In");
        UserSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSignInActionPerformed(evt);
            }
        });
        jPanel12.add(UserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        ShowUserPassSignIn.setText("Show Password");
        ShowUserPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUserPassSignInActionPerformed(evt);
            }
        });
        jPanel12.add(ShowUserPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jTabbedPane1.addTab("UserSignIn", jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RidernameSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel13.add(RidernameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 200, 60));

        RiderPassSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        RiderPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderPassSignInActionPerformed(evt);
            }
        });
        jPanel13.add(RiderPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 200, 60));

        ShowRiderPassSignIn.setText("Show Password");
        ShowRiderPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRiderPassSignInActionPerformed(evt);
            }
        });
        jPanel13.add(ShowRiderPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        RiderSignIn.setText("Sign In");
        RiderSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiderSignInActionPerformed(evt);
            }
        });
        jPanel13.add(RiderSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jTabbedPane1.addTab("RiderSignIn", jPanel13);

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminnameSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Nickname"));
        jPanel14.add(AdminnameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 200, 60));

        AdminPassSignIn.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        AdminPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPassSignInActionPerformed(evt);
            }
        });
        jPanel14.add(AdminPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, 60));

        ShowAdminPassSignIn.setText("Show Password");
        ShowAdminPassSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAdminPassSignInActionPerformed(evt);
            }
        });
        jPanel14.add(ShowAdminPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        AdminSignIn.setText("Sign In");
        AdminSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSignInActionPerformed(evt);
            }
        });
        jPanel14.add(AdminSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jTabbedPane1.addTab("AdminSignIn", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Connection getConnection(){
    Connection con;
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bismillah", "root", "InAllahWeTrust114");
        return con;
    } catch(SQLException e){
        return null;
    }
    }
    
    public void loadApplications(){
    Connection con = getConnection();
    String query = "SELECT * FROM ridersapp WHERE accept = 'no'";

    try{
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

        Object[] row;
        while(rs.next()){
            row = new Object[6]; 
            row[0] = rs.getString(1); 
            row[1] = rs.getString(2);
            row[2] = rs.getString(3); 
            row[3] = rs.getString(4);
            row[4] = rs.getString(5); 
            row[5] = rs.getString(7); 
            

            model.addRow(row);
        }
    } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
    
    
}
    
    public void loadApplications2(){
    Connection con = getConnection();
    String query = "SELECT * FROM ridersapp WHERE accept = 'yes'";

    try{
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);

        Object[] row;
        while(rs.next()){
            row = new Object[6]; 
            row[0] = rs.getString(1); 
            row[1] = rs.getString(2);
            row[2] = rs.getString(3); 
            row[3] = rs.getString(4);
            row[4] = rs.getString(5); 
            row[5] = rs.getString(7);

            model.addRow(row);
        }
    } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }

    }
    
    public void loadApplications3(){
    Connection con = getConnection();
    String query = "SELECT * FROM users";

    try{
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);

        Object[] row;
        while(rs.next()){
            row = new Object[4];
            row[0] = rs.getString(1);
            row[1] = rs.getString(2);
            row[2] = rs.getString(3);
            row[3] = rs.getString(5);

            model.addRow(row);
        }
    } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }

    }
    
    private void HomeSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSignInActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_HomeSignInActionPerformed

    private void UserSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSignUpBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_UserSignUpBtnActionPerformed

    private void HomeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_HomeExitActionPerformed

    private void RiderSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderSignUpBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_RiderSignUpBtnActionPerformed

    private void AdminSignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSignInBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(13);
    }//GEN-LAST:event_AdminSignInBtnActionPerformed

    private void HomeSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSignUpActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_HomeSignUpActionPerformed

    private void RiderPassRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderPassRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RiderPassRegActionPerformed

    private void ShowRiderPassSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRiderPassSignUpActionPerformed
        // TODO add your handling code here:
        if (ShowRiderPassSignUp.isSelected()) {
           RiderPassReg.setEchoChar((char)0);
        }
        else {
            RiderPassReg.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowRiderPassSignUpActionPerformed

    private void UserSignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSignInBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(11);
    }//GEN-LAST:event_UserSignInBtnActionPerformed

    private void RiderSignUpBtnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderSignUpBtnRegActionPerformed
        // TODO add your handling code here:
        String name1 = RiderFullNameReg.getText();
        String username1 = RiderUsernameReg.getText();
        String mobile1 = RiderMobileReg.getText();
        String vehicle1 = RiderVehicleReg.getText();
        String address1 = RiderAddressReg.getText();
        char[] passwordChar = RiderPassReg.getPassword();
        String password1 = new String(passwordChar);
        
        Connection con = getConnection();
        String query = "INSERT INTO ridersapp(fullname, username, mobile, vehicle, address, password, accept) VALUES(?, ?, ?, ?, ?, ?, ?)";

        try{
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, name1);
            ps.setString(2, username1);
            ps.setString(3, mobile1);
            ps.setString(4, vehicle1);
            ps.setString(5, address1);
            ps.setString(6, password1);
            ps.setString(7, "no");
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data inserted successfully!");
            RiderFullNameReg.setText("");
            RiderUsernameReg.setText("");
            RiderMobileReg.setText("");
            RiderVehicleReg.setText("");
            RiderAddressReg.setText("");
            RiderPassReg.setText("");
                  
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_RiderSignUpBtnRegActionPerformed

    private void ShowUserPassSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUserPassSignUpActionPerformed
        // TODO add your handling code here:
        if(ShowUserPassSignUp.isSelected()){
            UserPassReg.setEchoChar((char)0);
        }
        else{
            UserPassReg.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowUserPassSignUpActionPerformed

    private void UserSignUpConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSignUpConfirmBtnActionPerformed
        // TODO add your handling code here:
        String name1 = UserFullNameReg.getText();
        String username1 = UserUsernameReg.getText();
        char[] passwordChar = UserPassReg.getPassword();
        String password1 = new String(passwordChar);
        String mobile1 = UserMobileReg.getText();
        
        
        
        Connection con = getConnection();
        String query = "INSERT INTO users(fullname, username, password, phone) VALUES(?, ?, ?, ?)";

        try{
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, name1);
            ps.setString(2, username1);
            ps.setString(3, password1);
            ps.setString(4, mobile1);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data inserted successfully!");
            
            
            UserFullNameReg.setText("");
            UserUsernameReg.setText("");
            UserPassReg.setText("");
            UserMobileReg.setText("");
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_UserSignUpConfirmBtnActionPerformed

    private void RiderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RiderHistoryActionPerformed

    private void AcceptRidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRidersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(8);
        loadApplications();
        
    }//GEN-LAST:event_AcceptRidersActionPerformed

    private void SeeRidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeRidersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(9);
        loadApplications2();
    }//GEN-LAST:event_SeeRidersActionPerformed

    private void SeeUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeUsersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(10);
        loadApplications3();
    }//GEN-LAST:event_SeeUsersActionPerformed

    private void UserPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPassSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPassSignInActionPerformed

    private void ShowUserPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUserPassSignInActionPerformed
        // TODO add your handling code here:
        
        if(ShowUserPassSignIn.isSelected()){
            UserPassSignIn.setEchoChar((char)0);
        }
        else{
            UserPassSignIn.setEchoChar('*');
        }
        
    }//GEN-LAST:event_ShowUserPassSignInActionPerformed

    private void UserSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSignInActionPerformed
        // TODO add your handling code here:
        
    String uname = UsernameSignIn.getText();
    char[] passChar = UserPassSignIn.getPassword();
    String pass = new String(passChar);

    Connection con = getConnection();
    String query = "SELECT * FROM users WHERE username = ? AND password = ?";

    try{
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, uname);
        ps.setString(2, pass);
        ResultSet rs = ps.executeQuery();

        if(rs.next()){
            // Sign in successful
            JOptionPane.showMessageDialog(null, "Sign in successful!");
            UsernameSignIn.setText("");
            UserPassSignIn.setText("");
            // Add the index for the user panel
        } else {
            // Sign in failed
            JOptionPane.showMessageDialog(null, "Invalid username or password.");
        }
    } catch(HeadlessException | SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_UserSignInActionPerformed

    private void RiderSignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderSignInBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(12);
    }//GEN-LAST:event_RiderSignInBtnActionPerformed

    private void RiderPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderPassSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RiderPassSignInActionPerformed

    private void RiderSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiderSignInActionPerformed
        // TODO add your handling code here:
        
        String uname = RidernameSignIn.getText();
        char[] passChar = RiderPassSignIn.getPassword();
        String pass = new String(passChar);

        Connection con = getConnection();
        String query = "SELECT * FROM ridersapp WHERE username = ? AND password = ? AND accept = ?";

        try{
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, uname);
            ps.setString(2, pass);
            ps.setString(3, "yes");
            ResultSet rs = ps.executeQuery();

            if(rs.next()){
                // Sign in successful
                JOptionPane.showMessageDialog(null, "Sign in successful!");
                RidernameSignIn.setText("");
                RiderPassSignIn.setText("");
                // Add the index for the rider panel
            } else {
                // Sign in failed
                JOptionPane.showMessageDialog(null, "Invalid username or password.");
            }
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_RiderSignInActionPerformed

    private void ShowRiderPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRiderPassSignInActionPerformed
        // TODO add your handling code here:
        if (ShowRiderPassSignIn.isSelected()) {
           RiderPassSignIn.setEchoChar((char)0);
        }
        else {
            RiderPassSignIn.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowRiderPassSignInActionPerformed

    private void AdminPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPassSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPassSignInActionPerformed

    private void ShowAdminPassSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAdminPassSignInActionPerformed
        // TODO add your handling code here:
        
        if (ShowAdminPassSignIn.isSelected()) {
           AdminPassSignIn.setEchoChar((char)0);
        }
        else {
            AdminPassSignIn.setEchoChar('*');
        }
        
    }//GEN-LAST:event_ShowAdminPassSignInActionPerformed

    private void AdminSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSignInActionPerformed
        // TODO add your handling code here:
        
        String uname = AdminnameSignIn.getText();
        char[] passChar = AdminPassSignIn.getPassword();
        String pass = new String(passChar);

        Connection con = getConnection();
        String query = "SELECT * FROM admins WHERE username = ? AND password = ?";

        try{
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, uname);
            ps.setString(2, pass);
            ResultSet rs = ps.executeQuery();

            if(rs.next()){
                // Sign in successful
                JOptionPane.showMessageDialog(null, "Sign in successful!");
                AdminnameSignIn.setText("");
                AdminPassSignIn.setText("");
                // Add the index for the user panel
            } else {
                // Sign in failed
                JOptionPane.showMessageDialog(null, "Invalid username or password.");
            }
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AdminSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShohoJatriUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShohoJatriUI().setVisible(true);
        });
        
        
        
        /*try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bismillah", "root", "InAllahWeTrust114");
            System.out.print(con);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ShohoJatriUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptRide;
    private javax.swing.JButton AcceptRiders;
    private javax.swing.JButton Account;
    private javax.swing.JPasswordField AdminPassSignIn;
    private javax.swing.JButton AdminSignIn;
    private javax.swing.JButton AdminSignInBtn;
    private javax.swing.JTextField AdminnameSignIn;
    private javax.swing.JButton HistoryUser;
    private javax.swing.JButton HomeExit;
    private javax.swing.JButton HomeSignIn;
    private javax.swing.JButton HomeSignUp;
    private javax.swing.JButton RequestRide;
    private javax.swing.JTextField RiderAddressReg;
    private javax.swing.JTextField RiderFullNameReg;
    private javax.swing.JButton RiderHistory;
    private javax.swing.JTextField RiderMobileReg;
    private javax.swing.JPasswordField RiderPassReg;
    private javax.swing.JPasswordField RiderPassSignIn;
    private javax.swing.JButton RiderSignIn;
    private javax.swing.JButton RiderSignInBtn;
    private javax.swing.JButton RiderSignUpBtn;
    private javax.swing.JButton RiderSignUpBtnReg;
    private javax.swing.JTextField RiderUsernameReg;
    private javax.swing.JTextField RiderVehicleReg;
    private javax.swing.JTextField RidernameSignIn;
    private javax.swing.JButton SeeRiders;
    private javax.swing.JButton SeeUsers;
    private javax.swing.JCheckBox ShowAdminPassSignIn;
    private javax.swing.JCheckBox ShowRiderPassSignIn;
    private javax.swing.JCheckBox ShowRiderPassSignUp;
    private javax.swing.JCheckBox ShowUserPassSignIn;
    private javax.swing.JCheckBox ShowUserPassSignUp;
    private javax.swing.JTextField UserFullNameReg;
    private javax.swing.JTextField UserMobileReg;
    private javax.swing.JPasswordField UserPassReg;
    private javax.swing.JPasswordField UserPassSignIn;
    private javax.swing.JButton UserSignIn;
    private javax.swing.JButton UserSignInBtn;
    private javax.swing.JButton UserSignUpBtn;
    private javax.swing.JButton UserSignUpConfirmBtn;
    private javax.swing.JTextField UserUsernameReg;
    private javax.swing.JTextField UsernameSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
